// @ts-check

import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/.turbo/**',
      '**/coverage/**',
    ],
  },
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        // projectService discovers tsconfig.json per-package (turbo runs lint per workspace).
        // allowDefaultProject covers root-level .mjs config files (eslint.config.mjs itself).
        projectService: {
          allowDefaultProject: ['*.mjs', '*.cjs', '*.js'],
          defaultProject: './tsconfig.base.json',
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/strict-boolean-expressions': 'error',
    },
  },
  {
    // Vendored shadcn/ui primitives are generated by the shadcn CLI and regenerated on update —
    // we do not hand-edit them to satisfy our app-strict rules (edits would be lost, and the
    // upstream code is well-tested). Relax only the two rules that clash with shadcn's own style
    // for these generated files; all other rules still apply.
    files: [
      'packages/ui/src/components/ui/**/*.{ts,tsx}',
      'packages/ui/src/hooks/use-mobile.tsx',
    ],
    rules: {
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      // chart.tsx wraps recharts, whose public API is loosely typed (`any`) — these fire on the
      // vendored recharts interop, not on our own code.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
    },
  },
);
